[package]

name = "sdfgen"
version = "0.2.2"
authors = [ "Constantin Berhard <sdfgen.8.enormator@xoxy.net>" ]

[[bin]]

name = "sdfgen"

[dependencies]
image="*"
getopts="*"
byteorder="*"
num="*"
simple_parallel={git="https://github.com/ConnyOnny/simple_parallel.git"}
