[package]
name = "sdfgen"
version = "0.4.0"
authors = [ "Constantin Berhard <sdfgen.8.enormator@xoxy.net>", "Brett Lajzer <brett@brettlajzer.com>" ]

[[bin]]
name = "sdfgen"

[dependencies]
image = "^0.23.0"
getopts = "^0.2.21"
byteorder = "^1.3.4"
num = "^0.2.1"
rayon = "^1.3.0"
